### ISSUE TITLE
Gemini.parse_response_for_mode raises an error for unhandled response structure

### ISSUE THREAD

**Issue by vkryukov** [thmsmlr/instructor_ex#78]
When asking Gemini to summarize content that it finds objectionable (e.g., [this article](https://jhftss.github.io/A-New-Era-of-macOS-Sandbox-Escapes/)) it raises an error because `Gemini.parse_response_for_mode` only handles a happy path:

```
** (FunctionClauseError) no function clause matching in Instructor.Adapters.Gemini.parse_response_for_mode/2    
    
    The following arguments were given to Instructor.Adapters.Gemini.parse_response_for_mode/2:
    
        # 1
        :json_schema
    
        # 2
        %{
          "candidates" => [
            %{
              "finishReason" => "SAFETY",
              "index" => 0,
              "safetyRatings" => [
                %{
                  "category" => "HARM_CATEGORY_SEXUALLY_EXPLICIT",
                  "probability" => "NEGLIGIBLE"
                },
                %{
                  "category" => "HARM_CATEGORY_HATE_SPEECH",
                  "probability" => "NEGLIGIBLE"
                },
                %{
                  "category" => "HARM_CATEGORY_HARASSMENT",
                  "probability" => "NEGLIGIBLE"
                },
                %{
                  "category" => "HARM_CATEGORY_DANGEROUS_CONTENT",
                  "probability" => "MEDIUM"
                }
              ]
            }
          ],
          "modelVersion" => "gemini-1.5-flash-001",
          "usageMetadata" => %{"promptTokenCount" => 10842, "totalTokenCount" => 10842}
        }
    
    Attempted function clauses (showing 2 out of 2):
    
        defp parse_response_for_mode(:tools, %{"candidates" => [%{"content" => %{"parts" => [%{"functionCall" => %{"args" => args}}]}}]})
        defp parse_response_for_mode(:json_schema, %{"candidates" => [%{"content" => %{"parts" => [%{"text" => text}]}}]})
    
    (instructor 0.0.5) lib/instructor/adapters/gemini.ex:225: Instructor.Adapters.Gemini.parse_response_for_mode/2
    (instructor 0.0.5) lib/instructor/adapters/gemini.ex:214: Instructor.Adapters.Gemini.do_chat_completion/3
    (instructor 0.0.5) lib/instructor.ex:485: Instructor.do_adapter_chat_completion/2
    (instructor 0.0.5) lib/instructor.ex:432: Instructor.do_chat_completion/3
```

**Comment by thmsmlr** [comment]
Solved in the latest release, [{:instructor, "~> 0.1.0"}](https://hex.pm/packages/instructor/0.1.0)
