### ISSUE TITLE
Quickstart livebook fails to install instructor_ex

### ISSUE THREAD

**Issue by ospaarmann** [thmsmlr/instructor_ex#86]
I tried running the livebook locally as standalone and I get this error after the first cell:

```elixir
Mix.install(
  [
    {:instructor, path: Path.expand("../", __DIR__)}
  ],
  config: [
    instructor: [
      adapter: Instructor.Adapters.OpenAI,
      openai: [api_key: System.fetch_env!("LB_OPENAI_API_KEY")]
    ]
  ]
)
```

Error:

```
Could not compile :instructor, no "mix.exs", "rebar.config" or "Makefile" (pass :compile as an option to customize compilation, set it to "false" to do nothing)
Unchecked dependencies for environment dev:
* instructor (/Users/olespaarmann/Library/Application Support/livebook/autosaved/2024_12_07)
  could not find an app file at "_build/dev/lib/instructor/ebin/instructor.app". This may happen if the dependency was not yet compiled or the dependency indeed has no app file (then you can pass app: false as option)

** (Mix.Error) Can't continue due to errors on dependencies
    (mix 1.17.2) lib/mix.ex:588: Mix.raise/2
    (mix 1.17.2) lib/mix/tasks/deps.loadpaths.ex:48: Mix.Tasks.Deps.Loadpaths.run/1
    (mix 1.17.2) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.17.2) lib/mix.ex:947: anonymous fn/5 in Mix.install/2
    (elixir 1.17.2) lib/file.ex:1665: File.cd!/2
    (mix 1.17.2) lib/mix.ex:911: Mix.install/2
    #cell:setup:1: (file)
```

It works when I change the cell and remove the path:

```elixir
Mix.install(
  [
    :instructor
  ],
  config: [
    instructor: [
      adapter: Instructor.Adapters.OpenAI,
      openai: [api_key: System.fetch_env!("LB_OPENAI_API_KEY")]
    ]
  ]
)
```

**Comment by dewalor** [comment]
duplicate of https://github.com/thmsmlr/instructor_ex/issues/25
