### ISSUE TITLE
Error trying to run Ticket extraction example in local livebook

### ISSUE THREAD

**Issue by mratliff** [thmsmlr/instructor_ex#87]
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not an atom

    (erts 15.0) :erlang.function_exported({:parameterized, {Ecto.Embedded, %Ecto.Embedded{cardinality: :many, field: :tickets, owner: MeetingNotes, related: MeetingNotes.Ticket, on_cast: nil, on_replace: :raise, unique: true, ordered: true}}}, :to_json_schema, 0)
    (instructor 0.0.5) lib/instructor/json_schema.ex:292: Instructor.JSONSchema.for_type/1
    (instructor 0.0.5) lib/instructor/json_schema.ex:79: anonymous fn/2 in Instructor.JSONSchema.bfs_from_ecto_schema/2
    (elixir 1.17.2) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
    (instructor 0.0.5) lib/instructor/json_schema.ex:77: Instructor.JSONSchema.bfs_from_ecto_schema/2
    (instructor 0.0.5) lib/instructor/json_schema.ex:13: Instructor.JSONSchema.from_ecto_schema/1
    (instructor 0.0.5) lib/instructor.ex:536: Instructor.params_for_mode/3
    #cell:zich7572fcltdcw6:2: (file)

**Comment by camfeghali** [comment]
I'm getting the same error :(

**Comment by thmsmlr** [comment]
see #89 

Solved in the latest release, [{:instructor, "~> 0.1.0"}](https://hex.pm/packages/instructor/0.1.0)
